In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'3.0.6'

In [6]:
df=pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [10]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0


In [8]:
records=df.shape[0]
records

10000

In [12]:
num_fuel_types=df['fuel_type'].nunique()
num_fuel_types

3

In [15]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [16]:
max_fuel_efficiency=df['fuel_efficiency_mpg'].max()
max_fuel_efficiency

np.float64(41.2)

In [46]:
median_value_of_horsepower=df['horsepower'].median()
median_value_of_horsepower

np.float64(252.0)

In [47]:
the_most_frequent_horsepower=df['horsepower'].value_counts().idxmax()
the_most_frequent_horsepower

np.float64(252.0)

In [48]:
df['horsepower']=df['horsepower'].fillna(the_most_frequent_horsepower)

In [49]:
median_value_of_horsepower=df['horsepower'].median()
median_value_of_horsepower

np.float64(252.0)

In [38]:
Asia_df=df[df['origin']=='Asia'][['vehicle_weight','model_year']].head(7)
Asia_df

In [40]:
x=np.array(Asia_df)
x

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [41]:
XTX=x.T.dot(x)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [42]:
XTX_inv=np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [43]:
y=np.array([1100,1300,800,900,1000,1100,1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [44]:
w=(XTX_inv.dot(x.T)).dot(y)
w

array([0.13644777, 0.2327492 ])

In [45]:
w.sum()

np.float64(0.36919696904925486)